config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'cart', to: 'carts#show', as: :cart
  root 'products#index'
  get 'checkout', to: 'checkout#new', as: 'checkout'
  get '/best_selling', to: 'drugs#best_selling'
  resources :orders, only: [:show, :create]





  # products page 
  resources :products, only: [:index, :show] do
    post 'add_to_cart', on: :member
    get 'cart', on: :collection
    put 'update_cart', on: :collection
    delete 'remove_item', on: :collection
    collection do
      get :on_sale
      get :new_products
      get :recently_updated
    end
  end

  #categories page
  resources :categories, only: [:index, :show] do
    collection do
      get :otc
      get :prescription
      get :branded
      get :generic
    end
  end
end

app/views/shared/_header.html.erb
<<<<<<< HEAD
<!-- app/views/shared/_header.html.erb -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "psalms.png", alt: "Logo", class: "logo-img" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Categories", categories_path, class: "nav-link" %>
      </li>
       <li class="nav-item"><%= link_to 'Best Selling Drugs', best_selling_path, class: "nav-link" %></li>
      </ul>
 
    </div>
         <li>
  <%= link_to "View Cart (#{session[:cart]&.count.to_i})", cart_products_path %>
</li>

  </div>
</nav>
=======
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("psalms.png", alt: "Psalms 103 Pharmacy", height: "40") %>
    <% end %>

    <!-- Toggle button -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar links -->
    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
      <ul class="navbar-nav text-center">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About Us', about_us_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', contact_path, class: 'nav-link' %>
        </li>
        <% if current_user.present? %>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>

    <!-- View Cart aligned to the right -->
    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
       <%= link_to cart_path, class: 'nav-link' do %>
  <%= image_tag("shopping_cart_image.jpg", alt: "Shopping Cart", height: "20") %>
  View Cart (<%= cart_items_count %>)
<% end %>

      </li>
    </ul>
  </div>
</nav>
<header class="bg-primary text-white text-center py-4">
  <div class="container">
    <h1 class="display-4">Welcome to Psalms 103 Pharmacy Online</h1>
 
  </div>
</header>
<!-- Include Bootstrap's JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
>>>>>>> 3b64b9dd9150b006b7b2651e2644892e4e29d7c3