config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'cart', to: 'carts#show', as: :cart
  root 'products#index'
  get 'checkout', to: 'checkout#new', as: 'checkout'
  get '/best_selling', to: 'drugs#best_selling'
  resources :orders, only: [:show, :create]





  # products page 
  resources :products, only: [:index, :show] do
    post 'add_to_cart', on: :member
    get 'cart', on: :collection
    put 'update_cart', on: :collection
    delete 'remove_item', on: :collection
    collection do
      get :on_sale
      get :new_products
      get :recently_updated
    end
  end

  #categories page
  resources :categories, only: [:index, :show] do
    collection do
      get :otc
      get :prescription
      get :branded
      get :generic
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
<<<<<<< HEAD
    has_many :products

    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "id", "name", "updated_at"]
      end

      def self.ransackable_attributes(auth_object = nil)
        ['name', 'description'] + super
      end
    
      def self.ransackable_associations(auth_object = nil)
        ['products']
end
end
=======
  has_many :products, foreign_key: 'category_id'
  validates :name, presence: true
  validates :description, presence: true

  def self.ransackable_attributes(auth_object = nil)
    %w[id name description created_at updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    ["products"]
  end

  # ...
end
>>>>>>> 3b64b9dd9150b006b7b2651e2644892e4e29d7c3

app/controllers/categories_controller.rb
# app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :otc, :prescription, :branded, :generic]
  
    def index
        @products = Product.page(params[:page]).per(10)
      end
    
      def show
        @products = @category.products.page(params[:page]).per(10)
      end
    
      def otc
        @category = Category.find_or_create_by(name: 'OTC')
        @products = @category.products.page(params[:page]).per(10)
        render 'show'
      end
      
    
      def prescription
        @category = Category.find_or_create_by(name: 'Prescription')
        @products = @category.products.page(params[:page]).per(10)
        render 'show'
      end
      
    
      def branded
        @category = Category.find_or_create_by(name: 'Branded')
        @products = @category.products.page(params[:page]).per(10)
        render 'show'
      end
    
      def generic
        @category = Category.find_or_create_by(name: 'Generic')
        @products = @category.products.page(params[:page]).per(10)
        render 'show'
      end
    
      private
    
      def set_category
        @category = Category.find_by(name: params[:id])
      end
    end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_products_table.html.erb
<!-- app/views/categories/_products_table.html.erb -->
<% if products.present? %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% products.each do |product| %>
        <tr>
          <td>
            <% if product.image.present? %>
              <%= image_tag product.image.url, class: "img-thumbnail" %>
            <% else %>
              <p>Image Not Available</p>
            <% end %>
          </td>
          <td><%= link_to product.name, product_path(product) %></td>
          <td><%= number_to_currency(product.price) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No products found for <%= @category.capitalize %>.</p>
<% end %>

app/views/categories/branded.html.erb
<!-- app/views/categories/branded.html.erb -->
<h1>Branded Products</h1>
<%= render 'products_table', products: @products %>
<%= link_to 'Back to Categories', categories_path, class: 'btn btn-secondary mt-3' %>

app/views/categories/generic.html.erb
<!-- app/views/categories/generic.html.erb -->
<h1>Generic Products</h1>
<%= render 'products_table', products: @products %>
<%= link_to 'Back to Categories', categories_path, class: 'btn btn-secondary mt-3' %>

app/views/categories/index.html.erb
<!-- app/views/categories/index.html.erb -->
<h1>Categories</h1>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "OTC", otc_categories_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Prescription", prescription_categories_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Branded", branded_categories_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Generic", generic_categories_path, class: "nav-link" %>
  </li>
</ul>


<h1>Products</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <% if product.image.present? %>
            <%= image_tag product.image.url, class: "img-thumbnail" %>
          <% else %>
            <p>Image Not Available</p>
          <% end %>
        </td>
        <td><%= link_to product.name, product_path(product) %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= product.category.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @products %>

app/views/categories/otc.html.erb
<!-- app/views/categories/otc.html.erb -->
<h1>OTC Products</h1>
<%= render 'products_table', products: @products %>
<%= link_to 'Back to Categories', categories_path, class: 'btn btn-secondary mt-3' %>

app/views/categories/prescription.html.erb
<!-- app/views/categories/prescription.html.erb -->
<h1>Prescription Products</h1>
<%= render 'products_table', products: @products %>
<%= link_to 'Back to Categories', categories_path, class: 'btn btn-secondary mt-3' %>

app/views/categories/show.html.erb
<!-- app/views/categories/show.html.erb  -->
<h1><%= @category.name %> Products</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Category</th>
      <th>Image</th>
      <th>Name</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= @category.name %></td>
        <td>
          <% if product.image.present? %>
            <%= image_tag product.image.url, class: "img-thumbnail" %>
          <% else %>
            <p>Image Not Available</p>
          <% end %>
        </td>
        <td><%= link_to product.name, product_path(product) %></td>
        <td><%= number_to_currency(product.price) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @products %>

<%= link_to "Back to Categories", categories_path %>